spectaql:

introspection:
  schemaFile: sdl_console.gql


info:
  title: Console V2 - GraphQL API


servers:
  - url: 'https://dev-v3.rteappbuilder.com/query'
    description: Dev
    production: false

